### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by pAlkesz** [BME-MIT-IET/iet-hf2021-samurai-mashers#12]
Create a folder that contains the documentation about the tasks: creating BDD tests, creating Unit tests and adding gradle and CI to the project. The non-funcional characteristics task does not require any documentation since we already documented our analysis in that markdown file.

**Comment by Ilosviki** [comment]
I uploaded the documentation of the Unit tests and the coverages.

My commit: [Find the commit here](https://github.com/BME-MIT-IET/iet-hf2021-samurai-mashers/commit/bb016ddf68785d0a7fca0f265adb906995e7cd9d)

**Comment by zoliabraham** [comment]
Added Gradle and CI documentation.
[commit](https://github.com/BME-MIT-IET/iet-hf2021-samurai-mashers/commit/32d6aa7adf9b188e9c79c71371f4d96ef7ee2c64)
