### ISSUE TITLE
Creating Unit Tests

### ISSUE THREAD

**Issue by fabiancsenge** [BME-MIT-IET/iet-hf2021-samurai-mashers#9]

**Comment by fabiancsenge** [comment]
I refactored the code and wrote a couple of unit tests. @Ilosviki  please check the coverage and complete the tests if necessary.

[commit link](https://github.com/BME-MIT-IET/iet-hf2021-samurai-mashers/commit/42672e240cc3d83aba98e37a4af136faae1dfefc)

**Comment by Ilosviki** [comment]
First I checked the coverage with JaCoCo, then I completed the Unit tests. Now there's 98% Instruction Coverage and 100% Branch Coverage. (I also refactored some methods.)

My commit: [Find the commit here](https://github.com/BME-MIT-IET/iet-hf2021-samurai-mashers/commit/71768227dfaae01bbd4311db1431c72b4129bf58)

**Comment by fabiancsenge** [comment]
I checked the tests and the coverage and I think it's good enough.
